base: &base
  build: .
  command: /root/rpmbuild/scripts/build.sh
  volumes:
    - ./rpms:/mnt:rw

foo:
  <<: *base
  dockerfile: roles/foo/Dockerfile
  environment:
    ROLE_NAME: foo
    NGINX_VERSION: 1.13.8
    NGINX_SRPM_URL: http://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.13.8-1.el7_4.ngx.src.rpm
    REVISION: 12
    OPENSSL_VERSION: 1.0.2
    HEADERS_MORE_VERSION: 0.33

hoge:
  <<: *base
  dockerfile: roles/hoge/Dockerfile
  environment:
    ROLE_NAME: hoge
    NGINX_VERSION: 1.12.1
    NGINX_SRPM_URL: http://nginx.org/packages/centos/7/SRPMS/nginx-1.12.1-1.el7.ngx.src.rpm
    REVISION: 2
